language: php
php:
  - 5.5
  - 5.6
  #- hhvm
before_script:
  - phpenv config-rm xdebug.ini
install:
  - composer install --no-dev --quiet 
script: phpunit --bootstrap phpunit_test/tests/bootstrap.php phpunit_test/tests